# ------------------------------------------------------------------------------
#  ~/Gemfile
#  Provides package information to bundle all Ruby gem needed
#  for Jekyll and J1 template (managed by Ruby Gem Bundler)
#
#  Product/Info:
#  https://jekyll-one.com
#
#  Copyright (C) 2018 Juergen Adams
#
#  J1 Template is licensed under the MIT License.
#  See: https://github.com/jekyll-one/j1_template_mde/blob/master/LICENSE
#
# ------------------------------------------------------------------------------
#
#  To install all gem needed for Jekyll and J1 Template
#
#  bundle install
#
#  Note:  If all packages needed are installed, a list of all gem
#         and dependencies installed for the bundle can created
#         by running:
#
#         bundle list
#
# ------------------------------------------------------------------------------
#
#  If you see warnings like:
#
#   WARN: Unresolved specs during Gem::Specification.reset
#         cleanup your bundle by running:
#
#         gem cleanup
#
# ------------------------------------------------------------------------------

source "https://rubygems.org"
ruby RUBY_VERSION

# --------------------------------------------------------------------
# J1 Template is using Jekyll v3.7 and above
#
#   NOTE: Jekyll >= v3.5 is using Liquid V4 for templating.
#         Make sure that all liquid|Template code is of version 4.x
#
gem 'jekyll', '~> 3.8.4'
gem 'liquid', '~> 4.0'

# Default theme (J1 Template Material Design Elements) based on
# Bootstrap v4.1.1 and MD for Bootstrap v0.5.10.
#
gem 'j1_template_mde', '~> 2018.4.0'


# --------------------------------------------------------------------
# PRODUCTION: Gem needed for the Jekyll and J1 prod environment
#

# ---------------------------------------------------------
# Code highlighter Pygments (pygmentize) from Python
#
#   NOTE: Make sure a working Python environment is
#   available
#
gem 'pygments.rb', '>= 1.1.2'

# ---------------------------------------------------------
# XML|HTML processing
#
gem 'builder', '~> 3.2'
gem 'nokogiri', '>= 1.7.0.1'
gem 'nokogiri-pretty', '>= 0.1.0'
gem 'htmlbeautifier', '>= 1.2.1'

# ---------------------------------------------------------
# Additional Gem for Asciidoctor (template|plugin support)
#
gem 'slim', '~> 3.0.7'
gem 'thread_safe', '~> 0.3.5'
gem 'middleman-core', '~> 4.2', '>= 4.2.1'

# ---------------------------------------------------------
# Timezone support (multi-platform)
#
gem 'tzinfo', '>= 1.2.2'

# ---------------------------------------------------------
# Platform specific Gem
#

#   Windows does not include zoneinfo files, so bundle the 
#   tzinfo-data gem
#
gem "tzinfo-data" if Gem.win_platform?

#  Windows Directory Monitor (WDM) monitor directories
#  for changes
#
gem 'wdm', '>= 0.1.1' if Gem.win_platform?

# ---------------------------------------------------------
# If any (additional) plugins are used, they go here:
#
group :jekyll_plugins do
  gem 'asciidoctor', '>= 1.5.6'
  gem 'asciidoctor-pdf', '>= 1.5.0.alpha.16'
  gem 'jekyll-feed', ">= 0.9"
  gem 'jekyll-gist', '>= 1.5.0'
  gem 'jekyll-sitemap', '>= 1.2.0'
  gem 'jekyll-asciidoc', '>= 2.1.0'
  gem 'jekyll-redirect-from', '>= 0.13.0'
  gem 'jekyll-paginate-v2', '>= 1.9.4'
  gem 'jekyll-sass-converter', '>= 1.5.1'
end

# ------------------------------------------------------------------------------
# J1 Web Application specific RubyGems
#

# --------------------------------------------------------------------
# Define your Ruby version if the J1 web is used as an container-based
# web application, e.g. on Docker or a Heroku Dyno, to define and use
# of identical Ruby runtime environments.
#
# ruby '2.5.1'

# --------------------------------------------------------------------
# Define the build environment and the web server for J1 sites that
# runs as an web application. To improve the production (run-time)
# performance for the web, the RubyGems e.g Puma or Passenger can be
# used to replace the internal server WEBrick used by Jekyll for
# default.
# The web server Puma, a multi-threaded native Ruy-based web server
# can be used on ALL platforms. Passenger integrates the web server
# NginX but supported for Linux and Unix platforms only.
# For container-based apps, Rake can be used as a pre-processor engine
# running # tasks defined by a Rakefile prior running the app|web.
#
# gem 'passenger'
gem 'puma', '>= 3.12.0'
gem 'rake', '~> 12.0'
#
# -------------------------------------------------------------------
# If J1 is transformed into a (Rack and Sinatra based) Web
# application, the site can be secured using user authentication
# for accessing private pages. J1 is using the Omniauth stack for
# authentication. For default, the Omniauth (authentication) strategies
# for Github, Twitter, Facebook and Patreon are implemented.
#
gem 'execjs', '~> 2.4'

gem 'rack', '~> 2.0'
gem 'rack-cors', '>= 1.0.2'
gem 'rack-protection', '~> 2.0'
gem 'rack-ssl-enforcer', '~> 0.2'

gem 'sinatra', '~> 2.0.3'
gem 'sinatra-contrib', '~> 2.0.3'
gem 'sinatra-index', '~> 0.0.2'
#gem 'sinatra_auth_github', '~> 2.0'

gem 'omniauth', '>= 1.3.0'
gem 'omniauth-facebook', '>= 5.0.0'
gem 'omniauth-github', '>= 1.3.0'
gem 'omniauth-twitter', '>= 1.4.0'

# --------------------------------------------------------------------
# DEVELOPMENT: Gem needed for the Jekyll and J1 dev environment
#

# For the build (npm|yarn), J1 Template is using scss_lint
# for linting the SCSS (CSS) components:
#
group :development, :test do
  gem 'scss_lint', '~> 0.56.0'
  gem 'sass', '~> 3.5.0'
  gem 'bump', '~> 0.5.4'
end

